\ stenoforth32

\ перевод часто используемых имен слов в нижний регистр
: 2LIT, SWAP LIT, LIT, ;
SYNONYM c@                    C@
SYNONYM w@                    W@
SYNONYM c!                    C!
SYNONYM w!                    W!
SYNONYM c,                    C,
SYNONYM w,                    W,
SYNONYM d+                    D+
SYNONYM d-                    D-
SYNONYM d*                    D*
SYNONYM d/                    D/
\ SYNONYM dmax                  DMAX
\ SYNONYM dmin                  DMIN
SYNONYM dor                   DOR
SYNONYM dxor                  DXOR
SYNONYM dand                  DAND
SYNONYM dinvert               DINVERT
SYNONYM dlshift               DLSHIFT
SYNONYM drshift               DRSHIFT
SYNONYM d0<>                  D0<>
SYNONYM dnegate               DNEGATE
SYNONYM dabs                  DABS

SYNONYM dup                   DUP
SYNONYM 2dup                  2DUP
SYNONYM drop                  DROP
SYNONYM 2drop                 2DROP
SYNONYM swap                  SWAP
SYNONYM 2swap                 2SWAP
SYNONYM over                  OVER
SYNONYM 2over                 2OVER
SYNONYM nip                   NIP
SYNONYM tuck                  TUCK
SYNONYM rot                   ROT
SYNONYM -rot                  -ROT
SYNONYM pick                  PICK
SYNONYM roll                  ROLL

SYNONYM sp@                   SP@
SYNONYM sp!                   SP!
SYNONYM depth                 DEPTH
SYNONYM .sn                   .SN
SYNONYM >r                    >R
SYNONYM 2>r                   2>R
SYNONYM r>                    R>
SYNONYM 2r>                   2R>
SYNONYM r@                    R@
SYNONYM 2r@                   2R@
SYNONYM rp@                   RP@
SYNONYM rp!                   RP!
SYNONYM rdrop                 RDROP
SYNONYM rallot                RALLOT
SYNONYM s0                    S0
SYNONYM r0                    R0

SYNONYM char                  CHAR
SYNONYM [char]                [CHAR]
SYNONYM .bl                   .BL
SYNONYM .sn                   .SN
SYNONYM bl                    BL
SYNONYM space                 SPACE
SYNONYM spaces                SPACES
SYNONYM d.                    D.
SYNONYM cr                    CR
SYNONYM hex                   HEX
SYNONYM decimal               DECIMAL
SYNONYM type                  TYPE
SYNONYM or                    OR
SYNONYM xor                   XOR
SYNONYM and                   AND
SYNONYM invert                INVERT
SYNONYM lshift                LSHIFT
SYNONYM rshift                RSHIFT
SYNONYM dump                  DUMP
SYNONYM \eof                  \EOF
SYNONYM s>d                   S>D
SYNONYM (d.)                  (D.)

SYNONYM true                  TRUE
SYNONYM false                 FALSE
SYNONYM if                    IF
SYNONYM else                  ELSE
SYNONYM then                  THEN
SYNONYM case                  CASE
SYNONYM of                    OF
SYNONYM endof                 ENDOF
SYNONYM endcase               ENDCASE

SYNONYM begin                 BEGIN
SYNONYM again                 AGAIN
SYNONYM until                 UNTIL
SYNONYM while                 WHILE
SYNONYM repeat                REPEAT

SYNONYM do                    DO
SYNONYM ?do                   ?DO
SYNONYM ado                   aDO
SYNONYM i+                    I+
SYNONYM i                     I
SYNONYM j                     J
SYNONYM leave                 LEAVE
SYNONYM unloop                UNLOOP
SYNONYM loop                  LOOP
SYNONYM +loop                 +LOOP

SYNONYM create                CREATE
SYNONYM created               CREATED
SYNONYM does>                 DOES>
SYNONYM aligned               ALIGNED
SYNONYM align                 ALIGN
SYNONYM align-nop             ALIGN-NOP
SYNONYM align-bytes           ALIGN-BYTES

SYNONYM dp                    DP
SYNONYM here                  HERE
SYNONYM allot                 ALLOT
SYNONYM cell                  CELL
SYNONYM cells                 CELLS

SYNONYM constant              CONSTANT
SYNONYM variable              VARIABLE
SYNONYM value                 VALUE
SYNONYM 2variable             2VARIABLE
SYNONYM 2value                2VALUE
SYNONYM vect                  VECT
SYNONYM ->vect                ->VECT
SYNONYM ->variable            ->VARIABLE
SYNONYM user                  USER
SYNONYM user-value            USER-VALUE
SYNONYM user-create           USER-CREATE
SYNONYM user-allot            USER-ALLOT
SYNONYM to                    TO
SYNONYM allocate              ALLOCATE
SYNONYM resize                RESIZE
SYNONYM free                  FREE
SYNONYM throw                 THROW
SYNONYM recurse               RECURSE
SYNONYM latest                LATEST
SYNONYM last                  LAST
SYNONYM last-cfa              LAST-CFA
SYNONYM literal               LITERAL
SYNONYM 2literal              2LITERAL
SYNONYM fliteral              FLITERAL
SYNONYM lit,                  LIT,
SYNONYM slit,                 SLIT,
SYNONYM rlit,                 RLIT,
SYNONYM 2lit,                 2LIT,
SYNONYM dlit,                 DLIT,
SYNONYM compile,              COMPILE,
SYNONYM [compile]             [COMPILE]
SYNONYM number?               NUMBER?
SYNONYM :noname               :NONAME
SYNONYM erase                 ERASE
SYNONYM fill                  FILL
SYNONYM compare               COMPARE
SYNONYM search                SEARCH
SYNONYM cmove>                CMOVE>
SYNONYM cmove                 CMOVE
SYNONYM move                  MOVE
SYNONYM emit                  EMIT
SYNONYM spmove                SPMOVE
SYNONYM spdrop                SPDROP
SYNONYM sp>mem                SP>MEM
SYNONYM key                   KEY
SYNONYM within                WITHIN
SYNONYM min                   MIN
SYNONYM max                   MAX
SYNONYM abs                   ABS
SYNONYM negate                NEGATE
SYNONYM mod                   MOD
SYNONYM /mod                  /MOD
SYNONYM umod                  UMOD
SYNONYM evaluate              EVALUATE
SYNONYM postpone              POSTPONE
SYNONYM execute               EXECUTE
SYNONYM immediate             IMMEDIATE
SYNONYM base                  BASE
SYNONYM state                 STATE
SYNONYM warning               WARNING

SYNONYM s,                    S,
SYNONYM s"                    S"
SYNONYM abort"                ABORT"
SYNONYM nextword              NextWord
SYNONYM wordbyaddr            WordByAddr
SYNONYM parse-name            PARSE-NAME
SYNONYM parse                 PARSE

SYNONYM forth                 FORTH
SYNONYM vocabulary            VOCABULARY
SYNONYM order                 ORDER
SYNONYM only                  ONLY
SYNONYM also                  ALSO
SYNONYM definitions           DEFINITIONS
SYNONYM previous              PREVIOUS
SYNONYM context               CONTEXT
SYNONYM current               CURRENT
SYNONYM module:               MODULE:
SYNONYM ;module               ;MODULE
SYNONYM notfound              NOTFOUND
SYNONYM sfind                 SFIND

SYNONYM words                 WORDS
SYNONYM id.                   ID.
SYNONYM name>                 NAME>
SYNONYM name>f                NAME>F
SYNONYM name>c                NAME>C
SYNONYM seet                  SEET
SYNONYM set-opt               SET-OPT
SYNONYM dis-opt               DIS-OPT

SYNONYM exit                  EXIT
SYNONYM task:                 TASK:
SYNONYM start                 START
SYNONYM stop                  STOP
SYNONYM suspend               SUSPEND
SYNONYM resume                RESUME
SYNONYM pause                 PAUSE

SYNONYM >in                   >IN
SYNONYM x>in                  X>IN
SYNONYM xdp                   XDP
SYNONYM source                SOURCE
SYNONYM xsource               XSOURCE
SYNONYM source-id             SOURCE-ID
SYNONYM curstr                CURSTR
SYNONYM xcurstr               XCURSTR
SYNONYM count                 COUNT
SYNONYM xfp                   XFP
SYNONYM tib                   TIB
SYNONYM #tib                  #TIB
SYNONYM file-position         FILE-POSITION
SYNONYM reposition-file       REPOSITION-FILE
SYNONYM xn                    XN
SYNONYM $label                $LABEL
SYNONYM choose                CHOOSE
SYNONYM i:                    I:
SYNONYM export                EXPORT
SYNONYM //                    \
SYNONYM ///                   \EOF
